name: "Helm push to ECR"
description: "Composite workflow to push a helm chart"
inputs:
  runs-on:
    type: string
    required: false
    default: ubuntu-latest
    description: "OS to run the job on"
  chart-path:
    required: true
    description: "Helm chart path"
    default: "."
  ecr-region:
    type: string
    required: true
    description: "ECR region"   
  ecr-repo:
    type: string
    required: true
    description: "ECR repo" 
  version:   
    type: string
    required: true
    description: "Chart versioning" 

runs:
  using: composite
  steps:
  
  - name: Authenticate ECR authenticate
    shell: bash
    run: aws ecr get-login-password --region  ${{ inputs.ecr-region }} | helm registry login --username AWS --password-stdin  ${{ inputs.ecr-repo }}

  - name: Chart versioning 
    shell: bash
    run: |
      sed -i "s/^version:.*$/version: ${{ inputs.version }}/" ${{ inputs.chart-path }}/Chart.yaml
      sed -i "s/^appVersion:.*$/appVersion: ${{ inputs.version }}/" ${{ inputs.chart-path }}/Chart.yaml


  - name: helm push from ECR
    shell: bash
    run: | 
      helm package ${{ inputs.chart-path }} 
      helm push $(ls *.tgz) oci://${{ inputs.ecr-repo }} 
 