name: "Test docker Build & ECR Push"
on:
  push:
    paths:
      - "**"
      - ".**"

env:
  REPO: 956994857092.dkr.ecr.us-east-2.amazonaws.com
  IMAGE_NAME: test
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ID }} 
  AWS_REGION: us-east-2

jobs:
  docker-image-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Docker build and Push image to ECR
      uses: accuknox/common-gh-actions/actions/docker-push@main
      with:
        repo: ${{ env.REPO }}
        image-name: ${{ env.IMAGE_NAME }}
        tag: ${{ github.ref_name }}
        docker-context: src/
