name: "Test docker Build & scan"
on:
  push:
    paths:
      - "**"
      - ".**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ID }} 
  REPO: 956994857092.dkr.ecr.us-east-2.amazonaws.com
  IMAGE_NAME: test
  

jobs:
  docker-image-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Docker build and Trivy scan
      uses: accuknox/common-gh-actions/actions/docker-scan@main
      with:
        repo: ${{ env.REPO }}
        image-name: ${{ env.IMAGE_NAME }}
        tag: ${{ github.run_number }}
        s3-bucket-name: accuknox-trivy-test
        trivy-exit-code: 0
        trivy-severity: HIGH,CRITICAL
        docker-context: src/
