name: "Test ci-test-go reusable workflow"

on:
  pull_request_target:
    branches:
    - "*"

jobs:
  go:
    uses: accuknox/common-gh-actions/.github/workflows/go-checks.yml@main   
    with:
      go-version: v1.19
      working-directory: .
      go-fmt: true
      go-lint: true
      go-sec: true
      go-build: true
      go-test: true
      go-swagger: true
      go-build-cmd: "go build ."
