name: "Checkout code"
description: "Composite workflow to checkout code"

runs:
  using: composite
  steps:
  - name: Checkout source
    if: ( github.event_name == 'pull_request' || github.event_name == 'pull_request_target' )
    uses: actions/checkout@v2
    with:
      ref: ${{ github.event.pull_request.head.sha }}

  - name: Checkout source
    if: ${{ startsWith(github.ref, 'refs/tags/v') }} 
    uses: actions/checkout@v2